### ISSUE TITLE
pip install elasticluster fail in python 2.7

### ISSUE THREAD

**Issue by PeterVermont** [gc3-uzh-ch/elasticluster#232]
[andrewsp@sciget anaconda]$ python --version
Python 2.7.11 :: Anaconda 2.5.0 (64-bit)
[andrewsp@sciget anaconda]$ pip --version
pip 8.0.3 from /home/andrewsp/anaconda2/lib/python2.7/site-packages (python 2.7)
[andrewsp@sciget anaconda]$ pip install elasticluster --no-cache-dir
Collecting elasticluster
  Downloading elasticluster-1.2.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 5.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-O52xky/elasticluster/setup.py", line 31, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-O52xky/elasticluster

**Comment by PeterVermont** [comment]
This now works. Perhaps you guys changed something? I think the error had something to do with the version of setuptools. 

My version:

 easy_install --version
setuptools 20.1.1 from /home/andrewsp/anaconda2/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg (Python 2.7)

**Comment by Shadowphax** [comment]
Nope, doesn't work with setuptools 20.1.1 
I had to go as far back as setuptools v7. Anything after 7 doesn't work. Ofcourse this is only for elasticluster-1.2. Elasticluster-1.3 works fine though under the latest setuptools.

**Comment by Shadowphax** [comment]
.... nevermind. It may work after the setuptools version changed but other dependencies require that a minimum of setuptools v11 for the novaclient
