### ISSUE TITLE
Pip install not working with Python 2.7.6

### ISSUE THREAD

**Issue by tobympotter** [gc3-uzh-ch/elasticluster#306]
Hello, 

I am trying to install elasticluster using pip with Python 2.7.6. The installation fails with this error message.

# pip install elasticluster
Downloading/unpacking elasticluster
  Downloading elasticluster-1.2.tar.gz (1.3MB): 1.3MB downloaded
  Running setup.py egg_info for package elasticluster
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_root/elasticluster/setup.py", line 31, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_root/elasticluster/setup.py", line 31, in <module>

    del sdist.finders[:]

AttributeError: 'module' object has no attribute 'finders'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/elasticluster
Storing complete log in /root/.pip/pip.log

Kind regards,
Toby

**Comment by riccardomurri** [comment]
Hello Toby,

ElastiCluster 1.2 (the code currently on PyPI) is quite old; the new version 1.3 will be out in 2 weeks and this issue does not happen there.  I would rather not make a new 1.2.1 release that will be obsolete in a few days.

Until version 1.3 is released, I would advise you to install the "master" branch code from GitHub: <http://elasticluster.readthedocs.io/en/latest/install.html#installing-development-code-from-github>.
